[ntp] Update and fix do_rootfs error
WARNING: openvision-enigma2-image-1.0-r0 do_rootfs: ntpdate.postinst returned 1, marking as unpacked only, configuration required on target.
ERROR: openvision-enigma2-image-1.0-r0 do_rootfs: Postinstall scriptlets of ['ntpdate'] have failed. If the intention is to defer them to first boot,
then please place them into pkg_postinst_ontarget_${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.