mpd: Fix build against latest fmt
Introduced with commit:
https://github.com/fmtlib/fmt/commit/d70729215fba1d54862e407b626abf86ddf409bf

/home/hains/openpli-dm920-python3/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/mpd/0.23.14+git/recipe-sysroot/usr/include/
fmt/base.h:1383:29: error: passing 'const fmt::v10::formatter<std::__exception_ptr::exception_ptr>' as 'this' argument discards qualifiers [-fpermissive]