[exteplayer3] Fix ERROR: Nothing RPROVIDES 'librtmp'
ERROR: Nothing RPROVIDES 'librtmp' (but /home/raed/build_image/DM920/openpli-dreambox-oe-core/meta-openpli/recipes-multimedia/exteplayer3/exteplayer3.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'librtmp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['librtmp']
ERROR: Required build target 'exteplayer3' has no buildable providers.
Missing or unbuildable dependency chain was: ['exteplayer3', 'librtmp']