[wsdd] Fix unused result error openembedded/openembedded-core@4c2d64c
 wsdd.c: In function 'readSmbConf':
| wsdd.c:201:17: error: ignoring return value of 'fgets' declared with attribute 'warn_unused_result' [-Werror=unused-result]
|   201 |                 fgets(cd_name, sizeof(cd_name)-1, fp);
|       |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| wsdd.c:212:17: error: ignoring return value of 'fgets' declared with attribute 'warn_unused_result' [-Werror=unused-result]
|   212 |                 fgets(cd_workgroup, sizeof(cd_workgroup)-1, fp);
|       |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

cherry-pick > https://github.com/Hains/openpli-dm920-python3/commit/cffdc844545f9f95987b492ca91fe9dbd283f575