[upx] Update to fix error
Fix:
ERROR: 275 unbuildable tasks were found.###############################                                                             | ETA:  0:00:01
These are usually caused by circular dependencies and any circular dependency chains found will be printed below. Increase the debug level to see a list of unbuildable tasks.

Identifying dependency loops (this may take a short while)...

ERROR:
Dependency loop #1 found:
  Task virtual:native:/meta-openpli/recipes-core/upx/upx_4.2.4.bb:do_collect_spdx_deps (dependent Tasks ['quilt-native_0.68.bb:do_populate_sysroot', 'cmake-native_3.31.5.bb:do_create_spdx', 'ninja_1.12.1.bb:do_create_spdx', 'upx_4.2.4.bb:do_unpack'])