[fio] Fix for MIPS undefined __atomic_load_8 /libexec/mipsel-oe-linux/gcc/mipsel-oe-linux/15.2.0/ld: verify.o: undefined reference to symbol '__atomic_load_8@@LIBATOMIC_1.0' /libexec/mipsel-oe-linux/gcc/mipsel-oe-linux/15.2.0/ld: /home/raed/build_image/DM520/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/fio/3.41/recipe-sysroot/usr/lib/libatomic.so.1: error adding symbols: DSO missing from command line