[gstreamer1.0-libav] Fix build against ffmpeg 7.0.1 Declaration read-probe() function has been moved from structure AVInputFormat in the avformat.h header file to structure FFInputFormat in the demux.h header file.
Add demux.h header file to HEADERS so it will end up in the 'include' directory.

gstavdemux.c.o -c ../gst-libav-1.24.3/ext/libav/gstavdemux.c
| ../gst-libav-1.24.3/ext/libav/gstavdemux.c: In function 'gst_ffmpegdemux_type_find':
| ../gst-libav-1.24.3/ext/libav/gstavdemux.c:1403:16: error: 'AVInputFormat' has no member named 'read_probe'
|  1403 |   if (in_plugin->read_probe &&
|       |

See:
FFmpeg/FFmpeg@b800327

Duplicate in_plugin as FFInputFormat has no member 'name'.

Turn 'incompatible-pointer-types' error into warning.

 ../gst-libav-1.24.3/ext/libav/gstavprotocol.c:272:28: warning: passing argument 6 of 'avio_alloc_context'
 from incompatible pointer type [-Wincompatible-pointer-types]
|   272 |       gst_ffmpegdata_read, gst_ffmpegdata_write, gst_ffmpegdata_seek);
|       |

Follow: https://github.com/Hains/openpli-dm920-python3/commit/fb46bfffdc3c259f2f0f07df87c887fed188bc01