[kodi] fix GLUtils missing KHR debug constants
| ../../../sources/stb-kodi-dm7080-22.0+gitr/xbmc/utils/GLUtils.cpp:91:7: error: 'GL_DEBUG_SEVERITY_NOTIFICATION_KHR' was not declared in this scope
|    91 |     X(GL_DEBUG_SEVERITY_NOTIFICATION_KHR),
|       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| ../../../sources/stb-kodi-dm7080-22.0+gitr/xbmc/utils/GLUtils.cpp:29:31: note: in definition of macro 'X'
|    29 | #define X(VAL) std::make_pair(VAL, #VAL)
|       |                               ^~~
| ../../../sources/stb-kodi-dm7080-22.0+gitr/xbmc/utils/GLUtils.cpp:86:68: error: invalid initialization of reference of type 'std::pair<unsigned int, std::basic_string_view<char> > (&&)[4]' from expression of type '<brace-enclosed initializer list>'
|    86 | constexpr auto glErrorSeverity = make_map<GLenum, std::string_view>({
|       |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~