layer.conf: Remove patch-status from Qa error
e.g.
ERROR: groff-native-1.22.4-r1 do_patch: QA Issue: Missing Upstream-Status in patch
/home/hains/openpli-dm920-python3/meta-openpli/recipes-extended/groff/groff/groff-1.22.4-signbit-def-1.patch
Please add according to https://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines#Patch_Header_Recommendations:_Upstream-Status . [patch-status]

Introduced:
https://git.openembedded.org/openembedded-core/commit/?h=master-next&id=61a881fdbe8b5a21c6276b8a5d06cc30486b1eb3