enigma2: Fix build with c++17
std c++17 is default with GCC 11 now.

keyword register is deprecated since c++11, and warning is error now.
Remove 'register' keywords from header files python.

/home/hains/openpli-dm8000-oe-core/build/tmp/work/mips32el-oe-linux/enigma2/2.7+gitAUTOINC+b0772c277f-r0/recipe-sysroot/usr/include/
python2.7/unicodeobject.h:593:23: error: ISO C++17 does not allow 'register' storage class specifier [-Werror=register]
|   593 |     register wchar_t *w,        /* wchar_t buffer */
|       |                       ^
| In file included from /home/hains/openpli-dm8000-oe-core/build/tmp/work/mips32el-oe-linux/enigma2/2.7+
gitAUTOINC+b0772c277f-r0/recipe-sysroot/usr/include/python2.7/Python.h:97,
|                  from <command-line>:
| /home/hains/openpli-dm8000-oe-core/build/tmp/work/mips32el-oe-linux/enigma2/2.7+gitAUTOINC+b0772c277f-r0/recipe-sysroot/usr/include/
python2.7/stringobject.h:173:24: error: ISO C++17 does not allow 'register' storage class specifier [-Werror=register]
|   173 |     register PyObject *obj,     /* string or Unicode object */