dreambox-enigma2-config: Add missing skin.xml file (#32)
ERROR: /home/hains/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config.bb: Unable to get checksum
for dreambox-enigma2-config SRC_URI entry skin_box.xml: file could not be found
The following paths were searched: