libdreamdvd: Update move-function-pointer-away-from-header patch
Don't remove function declarations to fix error:

 ../git/main.c: In function 'ddvd_run':
| ../git/main.c:828:25: error: implicit declaration of function 'a52_init' [-Wimplicit-function-declaration]
|   828 |                 state = a52_init(0);    //init AC3 Decoder
|       |                         ^~~~~~~~

Introduced with gcc-14.

Declare pointers as extern to avoid multiple definition like:

 /home/hains/openpli-dm920-python3/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/libdreamdvd/1.0+git/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi/../../
libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/14.1.0/ld: .libs/main.o:/usr/src/debug/libdreamdvd/1.0+git/a52dec.h:62: multiple definition of `state';
.libs/a52_dec.o:/usr/src/debug/libdreamdvd/1.0+git/a52dec.h:62: first defined here

Which is also the purpose of this patch in the first place.

Declare pointer declarations extern in the dec.c file breaks compilation Enigma2, due to undefined references.